version: '3.3'

services:
    app:
        build: .
        restart: always
        entrypoint: ./scripts/start_bot.sh
        environment:
            PYTHONUNBUFFERED: 1
        volumes:
            - .:/app
        depends_on:
            - mongodb

    mongodb:
        image: mongo
        restart: always
